steps:
  - label: ":pipeline::kibana::seedling: Trigger Kibana Serverless Tests for ${ENVIRONMENT}"
    trigger: kibana-serverless
    build:
      env:
        ENVIRONMENT: ${ENVIRONMENT}
      message: Triggered by pipeline.tests.qa.yaml
      branch: $BUILDKITE_BRANCH
      commit: $BUILDKITE_COMMIT
  - wait: ~

  - label: ":cookie: Bake period of 24 hours"
    command: "sleep 86400"
