steps:
  - label: ":pipeline::kibana::seedling: Trigger Kibana Serverless Tests for ${ENVIRONMENT}"
    trigger: kibana-serverless
    build:
      env:
        ENVIRONMENT: ${ENVIRONMENT}
      message: Triggered by pipeline.tests.qa.yaml
      branch: $BUILDKITE_BRANCH
      commit: $BUILDKITE_COMMIT
      name: Serverless tests

  - label: ":pipeline::kibana::seedling: Trigger RAC Alert Load tests for ${ENVIRONMENT}"
    trigger: appex-qa-rac-alert-load
    build:
      env:
        ENVIRONMENT: ${ENVIRONMENT}
      message: Triggered by pipeline.tests.qa.yaml
      branch: $BUILDKITE_BRANCH
      commit: $BUILDKITE_COMMIT
      name: RAC Alert load tests
